# Build settings
encoding:           UTF-8
timezone:           Europe/Berlin
markdown:           kramdown
highlighter:        rouge
permalink:          /:title
plugins:            [jekyll-sitemap, jekyll-seo-tag, jekyll-email-protect, jekyll-multiple-languages-plugin]

# Configure the collections
collections:
  artists:
    output: false
  locations:
    output: false
  sponsors:
    output: false

# Exclude files from the build
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .ruby-version
  - vendor # required for CI environment
  - tools

# Translation settings
languages: ["de", "en"]
exclude_from_localizations:
  - assets
  - manifest.json

# compress_html:
#   blanklines: true


# Metadata for the site
title:		          "Spektakel Landshut"
url:                "https://spektakel.la"
description:	      "Website des internationalen Straßenkunstfestivals Spektakel Landshut. Hier finden Sie alle Informationen zu Künstlern, Programm, Lageplan, etc."
description_short:	"Internationales Straßenkunstfestival"
description_event:  "Das internationale Straßenkunstfestival in Landshut bietet ein vielfältiges Programm mit Künstlern aus aller Welt. Lassen Sie sich von atemberaubenden Darbietungen, faszinierenden Performances und mitreißender Straßenkunst verzaubern."
organizer:
  name:             "Spektakel Production"
logo:               "/assets/img/spektakel-logo.png"
image:              "/assets/img/spektakel-logo.png"
poster2025:         "/assets/img/plakat2025.jpg"
image_opaque:       "/assets/img/spektakel-logo.jpg"
social:
  name:             "Spektakel Landshut"
  links:
    - https://www.facebook.com/Spektakel.Landshut
    - https://www.instagram.com/spektakel.landshut
festival_start:     2025-09-18
festival_end:       2025-09-21

