# Site Build Settings
# Build settings
markdown:           kramdown
highlighter:        rouge
permalink:          /:title
plugins:            [jekyll-sitemap, jekyll-seo-tag, jekyll-email-protect]


# Customise seo-settings
# author:              "Martin Hilz"
title:		          "Spektakel Landshut"
description:	      "Internationales Festival"
locale:             "de_DE"
logo:               "/assets/img/spektakel-logo.png"
social:
  name:             "Spektakel Landshut"
  links:
    - https://www.facebook.com/Spektakel.Landshut
    - https://www.instagram.com/spektakel.landshut
festival_start:     2024-09-11
festival_end:       2024-09-15


collections:
  artists:
    output: false
  locations:
    output: false