# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-email-protect]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Spektakel Landshut"
description:	       "Homepage des Straßenkünstler-Festivals Spektakel Landshut"
author:              "a big fan"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

collections:
  artists:
    output: false
  locations:
    output: false