# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-tag: 'G-V8PX2QY82M'
google-tagmanager-id: 'GTM-TK5422TV'


menu:
- {name: 'Startseite',    url: ''}
- {name: 'Künstler',      url: 'artists'}
- {name: 'Programm',      url: 'program'}
- {name: 'Nachtleben',    url: 'nightlife'}
- {name: 'Lageplan',      url: 'locations'}
- {name: 'Impressionen',  url: 'impressions'}
- {name: 'Sponsoren',     url: 'sponsors'}

menu_home_label: 'Startseite'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/paululele'}
- {icon: 'facebook', link:   'https://www.facebook.com/groups/102139009844851'}
- {icon: 'instagram', link:  'https://www.instagram.com/spektakel.landshut'}
# - {icon: 'envelope', link:   'mailto:hello@paulle.ca'}


offline_map:
  bounding_rect: [[48.5279617,12.1401661], [48.542035,12.161327]]
  icon_anchor: [15, 46]
  icon_size: [35, 46]


post_date_prefix: 'Veröffentlicht am'
