# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-tag: 'G-V8PX2QY82M'
google-tagmanager-id: 'GTM-TK5422TV'


menu:
- {name: 'Startseite',  url: ''}
# - {name: 'Programm',      url: 'program'}
# - {name: 'Locations',     url: 'locations'}
# - {name: 'Künstler',      url: 'artists'}
- {name: 'Impressionen',  url: 'impressions'}
- {name: 'Sponsoren',     url: 'sponsors'}
- {name: 'Impressum',     url: 'impressum'}
# - {name: 'Kontakt'        url: 'contact'}

menu_home_label: 'Startseite'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/paululele'}
- {icon: 'facebook', link:   'https://www.facebook.com/groups/102139009844851'}
- {icon: 'instagram', link:  'https://www.instagram.com/spektakel.landshut'}
# - {icon: 'envelope', link:   'mailto:hello@paulle.ca'}


offline_map:
  bounding_rect: [[48.5314991, 12.1457491], [48.5418557, 12.1562020]]
  icon_anchor: [16, 16]
  icon_size: [32, 32]


post_date_prefix: 'Veröffentlicht am'
